// Argument lengths of associated instructions
unsigned char size_table[16][16] = {
	{0,2,0,0,0,0,1,0,2,0,0,0,0,0,1,0},
	{0,2,0,0,0,0,1,0,1,0,0,0,0,0,1,0},
	{1,2,0,0,0,0,1,0,1,0,0,0,0,0,1,0},
	{1,2,0,0,0,0,1,0,1,0,0,0,0,0,1,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,2,2,2,0,1,0,0,0,2,0,2,2,1,0},
	{0,0,2,0,2,0,1,0,0,0,2,0,2,0,1,0},
	{1,0,0,0,0,0,1,0,1,0,2,0,0,0,1,0},
	{1,0,0,0,0,0,1,0,1,0,2,0,0,0,1,0}
};

// Offsets of data insertion points
unsigned char offset_table[16][16] = {
	{0,4,0,0,0,0,3,0,2,0,0,0,0,0,3,0},
	{0,4,0,0,0,0,3,0,1,0,0,0,0,0,3,0},
	{4,4,0,0,0,0,3,0,3,0,0,0,0,0,3,0},
	{4,4,0,0,0,0,6,0,3,0,0,0,0,0,3,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,4,1,4,0,3,0,0,0,3,0,3,1,3,0},
	{0,0,4,0,4,0,1,0,0,0,3,0,3,0,3,0},
	{2,0,0,0,0,0,1,0,4,0,2,0,0,0,1,0},
	{4,0,0,0,0,0,1,0,7,0,4,0,0,0,1,0}
};

// Non-prefixed gbz80 instructions
char* opcode_table[16][16] = {
	{"nop",   "ld",    "ld",    "inc",   "inc",   "dec",   "ld",    "rlca",
	 "ld",    "add",   "ld",    "dec",   "inc",   "dec",   "ld",    "rrca"},
	{"stop",  "ld",    "ld",    "inc",   "inc",   "dec",   "ld",    "rla",
	 "jr",    "add",   "ld",    "dec",   "inc",   "dec",   "ld",    "rra"},
	{"jr",    "ld",    "ld",    "inc",   "inc",   "dec",   "ld",    "daa",
	 "jr",    "add",   "ld",    "dec",   "inc",   "dec",   "ld",    "cpl"},
	{"jr",    "ld",    "ld",    "inc",   "inc",   "dec",   "ld",    "scf",
	 "jr",    "add",   "ld",    "dec",   "inc",   "dec",   "ld",    "ccf"},
	{"ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",
	 "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld"},
	{"ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",
	 "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld"},
	{"ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",
	 "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld"},
	{"ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "halt",  "ld",
	 "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld"},
	{"add",   "add",   "add",   "add",   "add",   "add",   "add",   "add",
	 "adc",   "adc",   "adc",   "adc",   "adc",   "adc",   "adc",   "adc"},
	{"sub",   "sub",   "sub",   "sub",   "sub",   "sub",   "sub",   "sub",
	 "sbc",   "sbc",   "sbc",   "sbc",   "sbc",   "sbc",   "sbc",   "sbc"},
	{"and",   "and",   "and",   "and",   "and",   "and",   "and",   "and",
	 "xor",   "xor",   "xor",   "xor",   "xor",   "xor",   "xor",   "xor"},
	{"or",    "or",    "or",    "or",    "or",    "or",    "or",    "or",
	 "cp",    "cp",    "cp",    "cp",    "cp",    "cp",    "cp",    "cp"},
	{"ret",   "pop",   "jp",    "jp",    "call",  "push",  "add",   "rst",
	 "ret",   "ret",   "jp",    "-",     "call",  "call",  "adc",   "rst"},
	{"ret",   "pop",   "jp",    "-",     "call",  "push",  "sub",   "rst",
	 "ret",   "reti",  "jp",    "-",     "call",  "-",     "sbc",   "rst"},
	{"ldh",   "pop",   "ld",    "-",     "-",     "push",  "and",   "rst",
	 "add",   "jp",    "ld",    "-",     "-",     "-",     "xor",   "rst"},
	{"ldh",   "pop",   "ld",    "di",    "-",     "push",  "or",    "rst",
	 "ld",    "ld",    "ld",    "ei",     "-",     "-",     "cp",    "rst"}
};

// Non-prefixed gbz80 parameters
char* param_table[16][16] = {
	{"",            "bc,$xxyy",  "(bc),a",     "bc",
	 "b",           "b",         "b,$xx",      "",
	 "($xxyy),sp",  "hl,bc",     "a,(bc)",     "bc",
	 "c",           "c",         "c,$xx",      ""},
	{"",           "de,$xxyy",  "(de),a",     "de",
	 "d",           "d",         "d,$xx",      "",
	 "$xx",         "hl,de",     "a,(de)",     "de",
	 "e",           "e",         "e,$xx",      ""},
	{"nz,$xx",      "hl,$xxyy",  "(hl+),a",    "hl",
	 "h",           "h",         "h,$xx",      "",
	 "z,$xx",       "hl,hl",     "a,(hl+)",    "hl",
	 "l",           "l",         "l,$xx",      ""},
	{"nc,$xx",      "sp,$xxyy",  "(hl-),a",    "sp",
	 "(hl)",        "(hl)",      "(hl),$xx",   "",
	 "c,$xx",       "hl,sp",     "a,(hl-)",    "sp",
	 "a",           "a",         "a,$xx",      ""},
	{"b,b",         "b,c",       "b,d",        "b,e",
	 "b,h",         "b,l",       "b,(hl)",     "b,a",
	 "c,b",         "c,c",       "c,d",        "c,e",
	 "c,h",         "c,l",       "c,(hl)",     "c,a"},
	{"d,b",         "d,c",       "d,d",        "d,e",
	 "d,h",         "d,l",       "d,(hl)",     "d,a",
	 "e,b",         "e,c",       "e,d",        "e,e",
	 "e,h",         "e,l",       "e,(hl)",     "e,a"},
	{"h,b",         "h,c",       "h,d",        "h,e",
	 "h,h",         "h,l",       "h,(hl)",     "h,a",
	 "l,b",         "l,c",       "l,d",        "l,e",
	 "l,h",         "l,l",       "l,(hl)",     "l,a"},
	{"(hl),b",      "(hl),c",    "(hl),d",     "(hl),e",
	 "(hl),h",      "(hl),l",    "",           "(hl),a",
	 "a,b",         "a,c",       "a,d",        "a,e",
	 "a,h",         "a,l",       "a,(hl)",     "a,a"},
	{"a,b",         "a,c",       "a,d",        "a,e",
	 "a,h",         "a,l",       "a,(hl)",     "a,a",
	 "a,b",         "a,c",       "a,d",        "a,e",
	 "a,h",         "a,l",       "a,(hl)",     "a,a"},
	{"b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a",
	 "a,b",         "a,c",       "a,d",        "a,e",
	 "a,h",         "a,l",       "a,(hl)",     "a,a"},
	{"b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a",
	 "b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a"},
	{"b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a",
	 "b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a"},
	{"nz",          "bc",        "nz,$xxyy",   "$xxyy",
	 "nz,$xxyy",    "bc",        "a,$xx",      "00h",
	 "z",           "",          "z,$xxyy",    "cb",
	 "z,$xxyy",     "$xxyy",     "a,$xx",      "08h"},
	{"nc",          "de",        "nc,$xxyy",   "",
	 "nc,$xxyy",    "de",        "$xx",        "10h",
	 "c",           "",          "c,$xxyy",    "",
	 "c,$xxyy",     "",          "a,$xx",      "18h"},
	{"($xx),a",     "hl",        "(c),a",      "",
	 "",            "hl",        "$xx",        "20h",
	 "sp,$xx",      "(hl)",      "($xxyy),a",  "",
	 "",            "",          "$xx",        "28h"},
	{"a,($xx)",     "af",        "a,(c)",      "",
	 "",            "af",        "$xx",        "30h",
	 "hl,sp+$xx",   "sp,hl",     "a,($xxyy)",  "",
	 "",            "",          "$xx",        "38h"}
};

// Prefixed gbz80 instructions
char *cb_opcode_table[16][16] = {
	{"rlc",   "rlc",   "rlc",   "rlc",   "rlc",   "rlc",   "rlc",   "rlc",   
	 "rrc",   "rrc",   "rrc",   "rrc",   "rrc",   "rrc",   "rrc",   "rrc"},
	{"rl",    "rl",    "rl",    "rl",    "rl",    "rl",    "rl",    "rl",    
	 "rr",    "rr",    "rr",    "rr",    "rr",    "rr",    "rr",    "rr"},
	{"sla",   "sla",   "sla",   "sla",   "sla",   "sla",   "sla",   "sla",   
	 "sra",   "sra",   "sra",   "sra",   "sra",   "sra",   "sra",   "sra"},
	{"swap",  "swap",  "swap",  "swap",  "swap",  "swap",  "swap",  "swap",
	 "srl",   "srl",   "srl",   "srl",   "srl",   "srl",   "srl",   "srl"},
	{"bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   
	 "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit"},
	{"bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   
	 "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit"},
	{"bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   
	 "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit"},
	{"bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   
	 "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit"},
	{"res",   "res",   "res",   "res",   "res",   "res",   "res",   "res",   
	 "res",   "res",   "res",   "res",   "res",   "res",   "res",   "res"},
	{"res",   "res",   "res",   "res",   "res",   "res",   "res",   "res",   
	 "res",   "res",   "res",   "res",   "res",   "res",   "res",   "res"},
	{"res",   "res",   "res",   "res",   "res",   "res",   "res",   "res",   
	 "res",   "res",   "res",   "res",   "res",   "res",   "res",   "res"},
	{"res",   "res",   "res",   "res",   "res",   "res",   "res",   "res",   
	 "res",   "res",   "res",   "res",   "res",   "res",   "res",   "res"},
	{"set",   "set",   "set",   "set",   "set",   "set",   "set",   "set",   
	 "set",   "set",   "set",   "set",   "set",   "set",   "set",   "set"},
	{"set",   "set",   "set",   "set",   "set",   "set",   "set",   "set",   
	 "set",   "set",   "set",   "set",   "set",   "set",   "set",   "set"},
	{"set",   "set",   "set",   "set",   "set",   "set",   "set",   "set",   
	 "set",   "set",   "set",   "set",   "set",   "set",   "set",   "set"},
	{"set",   "set",   "set",   "set",   "set",   "set",   "set",   "set",   
	 "set",   "set",   "set",   "set",   "set",   "set",   "set",   "set"}
};

// Prefixed gbz80 parameters
char *cb_param_table[16][16] = {
	{"b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a",
	 "b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a"},
	{"b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a",
	 "b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a"},
	{"b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a",
	 "b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a"},
	{"b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a",
	 "b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a"},
	{"0,b",  "0,c",  "0,d",  "0,e",  "0,h",  "0,l",  "0,(hl)",  "0,a",
	 "1,b",  "1,c",  "1,d",  "1,e",  "1,h",  "1,l",  "1,(hl)",  "1,a"},
	{"2,b",  "2,c",  "2,d",  "2,e",  "2,h",  "2,l",  "2,(hl)",  "2,a",
	 "3,b",  "3,c",  "3,d",  "3,e",  "3,h",  "3,l",  "3,(hl)",  "3,a"},
	{"4,b",  "4,c",  "4,d",  "4,e",  "4,h",  "4,l",  "4,(hl)",  "4,a",
	 "5,b",  "5,c",  "5,d",  "5,e",  "5,h",  "5,l",  "5,(hl)",  "5,a"},
	{"6,b",  "6,c",  "6,d",  "6,e",  "6,h",  "6,l",  "6,(hl)",  "6,a",
	 "7,b",  "7,c",  "7,d",  "7,e",  "7,h",  "7,l",  "7,(hl)",  "7,a"},
	{"0,b",  "0,c",  "0,d",  "0,e",  "0,h",  "0,l",  "0,(hl)",  "0,a",
	 "1,b",  "1,c",  "1,d",  "1,e",  "1,h",  "1,l",  "1,(hl)",  "1,a"},
	{"2,b",  "2,c",  "2,d",  "2,e",  "2,h",  "2,l",  "2,(hl)",  "2,a",
	 "3,b",  "3,c",  "3,d",  "3,e",  "3,h",  "3,l",  "3,(hl)",  "3,a"},
	{"4,b",  "4,c",  "4,d",  "4,e",  "4,h",  "4,l",  "4,(hl)",  "4,a",
	 "5,b",  "5,c",  "5,d",  "5,e",  "5,h",  "5,l",  "5,(hl)",  "5,a"},
	{"6,b",  "6,c",  "6,d",  "6,e",  "6,h",  "6,l",  "6,(hl)",  "6,a",
	 "7,b",  "7,c",  "7,d",  "7,e",  "7,h",  "7,l",  "7,(hl)",  "7,a"},
	{"0,b",  "0,c",  "0,d",  "0,e",  "0,h",  "0,l",  "0,(hl)",  "0,a",
	 "1,b",  "1,c",  "1,d",  "1,e",  "1,h",  "1,l",  "1,(hl)",  "1,a"},
	{"2,b",  "2,c",  "2,d",  "2,e",  "2,h",  "2,l",  "2,(hl)",  "2,a",
	 "3,b",  "3,c",  "3,d",  "3,e",  "3,h",  "3,l",  "3,(hl)",  "3,a"},
	{"4,b",  "4,c",  "4,d",  "4,e",  "4,h",  "4,l",  "4,(hl)",  "4,a",
	 "5,b",  "5,c",  "5,d",  "5,e",  "5,h",  "5,l",  "5,(hl)",  "5,a"},
	{"6,b",  "6,c",  "6,d",  "6,e",  "6,h",  "6,l",  "6,(hl)",  "6,a",
	 "7,b",  "7,c",  "7,d",  "7,e",  "7,h",  "7,l",  "7,(hl)",  "7,a"}
};

// List of prefixed instructions for quick comparison
char *cb_set[11] = {"bit","res","rl","rlc","rr","rrc","set","sla","sra","srl","swap"};

// Items included in Pokemon R/B/Y
char *gen1_items[16][16] = {
	{"[item 0x00]",    "Master Ball",    "Ultra Ball",     "Great Ball",
	 "Poke Ball",      "Town Map",       "Bicycle",        "?????",
	 "Safari Ball",    "Pokedex",        "Moon Stone",     "Antidote",
	 "Burn Heal",      "Ice Heal",       "Awakening",      "Paralyz Heal"},
	{"Full Restore",   "Max Potion",     "Hyper Potion",   "Super Potion",
	 "Potion",         "Boulder Badge",  "Cascade Badge",  "Thunder Badge",
	 "Rainbow Badge",  "Soul Badge",     "Marsh Badge",    "Volcano Badge",
	 "Earth Badge",    "Escape Rope",    "Repel",          "Old Amber"},
	{"Fire Stone",     "Thunderstone",   "Water Stone",    "HP Up",
	 "Protein",        "Iron",           "Carbos",         "Calcium",
	 "Rare Candy",     "Dome Fossil",    "Helix Fossil",   "Secret Key",
	 "?????",          "Bike Voucher",   "X Accuracy",     "Leaf Stone"},
	{"Card Key",       "Nugget",         "PP Up",          "Poke Doll",
	 "Full Heal",      "Revive",         "Max Revive",     "Guard Spec.",
	 "Super Repel",    "Max Repel",      "Dire Hit",       "Coin",
	 "Fresh Water",    "Soda Pop",       "Lemonade",       "S.S. Ticket"},
	{"Gold Teeth",     "X Attack",       "X Defense",      "X Speed",
	 "X Special",      "Coin Case",      "Oak's Parcel",   "Item Finder",
	 "Silph Scope",    "Poke Flute",     "Lift Key",       "Exp. All",
	 "Old Rod",        "Good Rod",       "Super Rod",      "PP Up"},
	{"Ether",          "Max Ether",      "Elixer",         "Max Elixer",
	 "B2F",            "B1F",            "1F",             "2F ",
	 "3F",             "4F",             "5F",             "6F",
	 "7F ",            "8F",             "9F",             "10F"},
	{"11F",            "B4F",            "[item 0x62]",    "[item 0x63]",
	 "[item 0x64]",    "[item 0x65]",    "[item 0x66]",    "[item 0x67]",
	 "[item 0x68]",    "[item 0x69]",    "[item 0x6A]",    "[item 0x6B]",
	 "[item 0x6C]",    "[item 0x6D]",    "[item 0x6E]",    "[item 0x6F]"},
	{"[item 0x70]",    "[item 0x71]",    "[item 0x72]",    "[item 0x73]",
	 "[item 0x74]",    "[item 0x75]",    "[item 0x76]",    "[item 0x77]",
	 "[item 0x78]",    "[item 0x79]",    "[item 0x7A]",    "[item 0x7B]",
	 "[item 0x7C]",    "[item 0x7D]",    "[item 0x7E]",    "[item 0x7F]"},
	{"[item 0x80]",    "[item 0x81]",    "[item 0x82]",    "[item 0x83]",
	 "[item 0x84]",    "[item 0x85]",    "[item 0x86]",    "[item 0x87]",
	 "[item 0x88]",    "[item 0x89]",    "[item 0x8A]",    "[item 0x8B]",
	 "[item 0x8C]",    "[item 0x8D]",    "[item 0x8E]",    "[item 0x8F]"},
	{"[item 0x90]",    "[item 0x91]",    "[item 0x92]",    "[item 0x93]",
	 "[item 0x94]",    "[item 0x95]",    "[item 0x96]",    "[item 0x97]",
	 "[item 0x98]",    "[item 0x99]",    "[item 0x9A]",    "[item 0x9B]",
	 "[item 0x9C]",    "[item 0x9D]",    "[item 0x9E]",    "[item 0x9F]"},
	{"[item 0xA0]",    "[item 0xA1]",    "[item 0xA2]",    "[item 0xA3]",
	 "[item 0xA4]",    "[item 0xA5]",    "[item 0xA6]",    "[item 0xA7]",
	 "[item 0xA8]",    "[item 0xA9]",    "[item 0xAA]",    "[item 0xAB]",
	 "[item 0xAC]",    "[item 0xAD]",    "[item 0xAE]",    "[item 0xAF]"},
	{"[item 0xB0]",    "[item 0xB1]",    "[item 0xB2]",    "[item 0xB3]",
	 "[item 0xB4]",    "[item 0xB5]",    "[item 0xB6]",    "[item 0xB7]",
	 "[item 0xB8]",    "[item 0xB9]",    "[item 0xBA]",    "[item 0xBB]",
	 "[item 0xBC]",    "[item 0xBD]",    "[item 0xBE]",    "[item 0xBF]"},
	{"[item 0xC0]",    "[item 0xC1]",    "[item 0xC2]",    "[item 0xC3]",
	 "HM01",           "HM02",           "HM03",           "HM04",
	 "HM05",           "TM01",           "TM02",           "TM03",
	 "TM04",           "TM05",           "TM06",           "TM07"},
	{"TM08",           "TM09",           "TM10",           "TM11",
	 "TM12",           "TM13",           "TM14",           "TM15",
	 "TM16",           "TM17",           "TM18",           "TM19",
	 "TM20",           "TM21",           "TM22",           "TM23"},
	{"TM24",           "TM25",           "TM26",           "TM27",
	 "TM28",           "TM29",           "TM30",           "TM31",
	 "TM32",           "TM33",           "TM34",           "TM35",
	 "TM36",           "TM37",           "TM38",           "TM39"},
	{"TM40",           "TM41",           "TM42",           "TM43",
	 "TM44",           "TM45",           "TM46",           "TM47",
	 "TM48",           "TM49",           "TM50",           "TM51",
	 "TM52",           "TM53",           "TM54",           "CANCEL (TM55)"}
};

// Items included in Pokemon G/S/C
char *gen2_items[16][16] = {
	{"?",              "Master Ball",     "Ultra Ball",      "Brightpowder",
	 "Great Ball",     "Poke Ball",       "Teru-Sama",       "Bicycle",
	 "Moon Stone",     "Antidote",        "Burn Heal",       "Ice Heal",
	 "Awakening",      "Paralyz Heal",    "Full Restore",    "Max Potion"},
	{"Hyper Potion",   "Super Potion",    "Potion",          "Escape Rope",
	 "Repel",          "Max Ether",       "Fire Stone",      "Thunderstone",
	 "Water Stone",    "Teru-Sama",       "HP Up",           "Protein",
	 "Iron",           "Carbos",          "Lucky Punch",     "Calcium"},
	{"Rare Candy",     "X Accuracy",      "Leaf Stone",      "Metal Powder",
	 "Nugget",         "Poke Doll",       "Full Heal",       "Revive",
	 "Max Revive",     "Guard Spec.",     "Super Repel",     "Max Repel",
	 "Dire Hit",       "Teru-Sama",       "Fresh Water",     "Soda Pop"},
	{"Lemonade",       "X Attack",        "Teru-Sama",       "X Defend",
	 "X Speed",        "X Special",       "Coin Case",       "Itemfinder",
	 "Teru-Sama",      "Exp. Share",      "Old Rod",         "Good Rod",
	 "Silver Leaf",    "Super Rod",       "PP Up",           "Ether"},
	{"Max Ether",      "Elixer",          "Red Scale",       "Secretpotion",
	 "S.S. Ticket",    "Mystery Egg",     "Clear Bell (C)",  "Silver Wing",
	 "Moomoo Milk",    "Quick Claw",      "Psncureberry",    "Gold Leaf",
	 "Soft Sand",      "Sharp Beak",      "Przcureberry",    "Burnt Berry"},
	{"Ice Berry",      "Poison Barb",     "King's Rock",     "Bitter Berry",
	 "Mint Berry",     "Red Apricorn",    "Tinymushroom",    "Big Mushroom",
	 "Silverpowder",   "Blu Apricorn",    "Teru-Sama",       "Amulet Coin",
	 "Ylw Apricorn",   "Grn Apricorn",    "Cleanse Tag",     "Mystic Water"},
	{"Twistedspoon",   "Wht Apricorn",    "Black Belt",      "Blk Apricorn",
	 "Teru-Sama",      "Pnk Apricorn",    "Blackglasses",    "Slowpoketail",
	 "Pink Bow",       "Stick",           "Smoke Ball",      "Nevermeltice",
	 "Magnet",         "Miracleberry",    "Pearl",           "Big Pearl"},
	{"Everstone",      "Spell Tag",       "Ragecandybar",    "GS Ball (C)",
	 "Blue Card (C)",  "Miracle Seed",    "Thick Club",      "Focus Band",
	 "Teru-Sama",      "Energypowder",    "Energy Root",     "Heal Powder",
	 "Revival Herb",   "Hard Stone",      "Lucky Egg",       "Card Key"},
	{"Machine Part",   "Egg Ticket (C)",  "Lost Item",       "Stardust",
	 "Star Piece",     "Basement Key",    "Pass",            "Teru-Sama",
	 "Teru-Sama",      "Teru-Sama",       "Charcoal",        "Berry Juice",
	 "Scope Lens",     "Teru-Sama",       "Teru-Sama",       "Metal Coat"},
	{"Dragon Fang",    "Teru-Sama",       "Leftovers",       "Teru-Sama",
	 "Teru-Sama",      "Teru-Sama",       "Mysteryberry",    "Dragon Scale",
	 "Berserk Gene",   "Teru-Sama",       "Teru-Sama",       "Teru-Sama",
	 "Sacred Ash",     "Heavy Ball",      "Flower Mail",     "Level Ball"},
	{"Lure Ball",      "Fast Ball",       "Teru-Sama",       "Light Ball",
	 "Friend Ball",    "Moon Ball",       "Love Ball",       "Normal Box",
	 "Gorgeous Box",   "Sun Stone",       "Polkadot Bow",    "Teru-Sama",
	 "Up-Grade",       "Berry",           "Gold Berry",      "Squirtbottle"},
	{"Teru-Sama",      "Park Ball",       "Rainbow Wing",    "Teru-Sama",
	 "Brick Piece",    "Surf Mail",       "LiteBlue Mail",   "Portrait Mail",
	 "Lovely Mail",    "Eon Mail",        "Morph Mail",      "Blue Sky Mail",
	 "Music Mail",     "Mirage Mail",     "Teru-Sama",       "TM01"},
	{"TM02",           "TM03",            "TM04",            "TM04",
	 "TM05",           "TM06",            "TM07",            "TM08",
	 "TM09",           "TM10",            "TM11",            "TM12",
	 "TM13",           "TM14",            "TM15",            "TM16"},
	{"TM17",           "TM18",            "TM19",            "TM20",
	 "TM21",           "TM22",            "TM23",            "TM24",
	 "TM25",           "TM26",            "TM27",            "TM28",
	 "TM28",           "TM29",            "TM30",            "TM31"},
	{"TM32",           "TM33",            "TM34",            "TM35",
	 "TM36",           "TM37",            "TM38",            "TM39",
	 "TM40",           "TM41",            "TM42",            "TM43",
	 "TM44",           "TM45",            "TM46",            "TM47"},
	{"TM48",           "TM49",            "TM50",            "HM01",
	 "HM02",           "HM03",            "HM04",            "HM05",
	 "HM06",           "HM07",            "HM08",            "HM09",
	 "HM10",           "HM11",            "HM12",            "CANCEL (HM13)"}
};
